# Some base configuration used to generate root_url and root_path helpers (lib/helpers.rb)

# host: 'example.com'
# path: '/'
# project: 'project directory'

# Deploy with Rsync
# http://nanoc.stoneship.org/docs/6-guides/#deploying-sites

# deploy:
#   default:
#     dst: username@123.456.78.910:/path/to/project

# http://nanoc.stoneship.org/docs/4-basic-concepts/#sites for a list of configuration options

text_extensions: [ 'css', 'erb', 'haml', 'htm', 'html', 'js', 'less', 'markdown', 'md', 'php', 'rb', 'sass', 'scss', 'txt', 'xhtml', 'xml' ]
output_dir: output
index_filenames: [ 'index.html' ]
enable_output_diff: false
data_sources:
  -
    type: filesystem_unified
    items_root: /
    layouts_root: /
